name: Jak na VŠE
favicon: null
layout_spectrum: 0.5704162197653204
typography_spectrum: 0.5823767445981503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.02996044885367155
purpose: []
